name: 'Uplink'
description: 'Decentralized cloud object storage that is affordable, easy to use, private, and secure'
inputs:
  satellite_url:
    description: 'Satellite URL'
    required: true
  api_key:
    description: 'API key'
    required: true
  passphrase:
    description: 'Passphrase'
    required: true
  function:
    description: 'Function type'
    required: true
  bucket:
    description: 'Bucket name'
    required: false
  dest:
    description: 'Destination path'
    required: false
  src:
    description: 'Source path'
    required: false
outputs:
  output:
    description: 'action output'
runs:
  using: 'node16'
  main: 'dist/packages/action/index.js'
